
-- 1. Create admin_users table
CREATE TABLE IF NOT EXISTS public.admin_users (
    email TEXT PRIMARY KEY,
    created_at TIMESTAMPTZ DEFAULT NOW()
);

-- Habilitar RLS para admin_users e garantir que ela pode ser lida
ALTER TABLE public.admin_users ENABLE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS "Permitir leitura de admin_users" ON public.admin_users;
CREATE POLICY "Permitir leitura de admin_users" ON public.admin_users FOR SELECT USING (true);

-- => ADICIONE SEU EMAIL AQUI ANTES DE RODAR O SCRIPT:
INSERT INTO public.admin_users (email) VALUES ('marcosmarinho485@gmail.com') ON CONFLICT DO NOTHING;

-- 2. Create products table
DROP TABLE IF EXISTS public.products CASCADE;
DROP TABLE IF EXISTS public.categories CASCADE;

CREATE TABLE IF NOT EXISTS public.categories (
    id TEXT PRIMARY KEY,
    name TEXT NOT NULL UNIQUE,
    description TEXT,
    created_at TIMESTAMPTZ DEFAULT NOW()
);

CREATE TABLE IF NOT EXISTS public.products (
    id TEXT PRIMARY KEY,
    category_id TEXT REFERENCES public.categories(id) ON DELETE SET NULL,
    name TEXT NOT NULL,
    description TEXT,
    default_price NUMERIC(10, 2) NOT NULL DEFAULT 0.00,
    pix_price NUMERIC(10, 2),
    monthly_fee NUMERIC(10, 2) DEFAULT 0.00,
    image_url TEXT,
    is_active BOOLEAN DEFAULT true,
    commercial_rules JSONB DEFAULT '{"allow_pix": true, "allow_boleto": true, "allow_card": true, "allow_financing": true, "max_boleto_installments": 3, "max_card_installments": 12}'::jsonb,
    created_at TIMESTAMPTZ DEFAULT NOW()
);

-- 3. Create tecnicos table
CREATE TABLE IF NOT EXISTS public.tecnicos (
    id SERIAL PRIMARY KEY,
    nome TEXT NOT NULL,
    categoria TEXT,
    tipo TEXT,
    descricao TEXT,
    telefone TEXT,
    email TEXT,
    lat DOUBLE PRECISION NOT NULL,
    lng DOUBLE PRECISION NOT NULL,
    vendedor_parceiro TEXT,
    created_at TIMESTAMPTZ DEFAULT NOW()
);

-- 4. Enable RLS
ALTER TABLE public.tecnicos ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.products ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.categories ENABLE ROW LEVEL SECURITY;

-- 5. Policies
DROP POLICY IF EXISTS "Leitura de tecnicos por todos" ON public.tecnicos;
CREATE POLICY "Leitura de tecnicos por todos" ON public.tecnicos FOR SELECT USING (true);

DROP POLICY IF EXISTS "Leitura de produtos por todos" ON public.products;
CREATE POLICY "Leitura de produtos por todos" ON public.products FOR SELECT USING (true);

DROP POLICY IF EXISTS "Leitura de categorias por todos" ON public.categories;
CREATE POLICY "Leitura de categorias por todos" ON public.categories FOR SELECT USING (true);

DROP POLICY IF EXISTS "Admin full access on products" ON public.products;
CREATE POLICY "Admin full access on products" ON public.products FOR ALL USING (
    EXISTS (SELECT 1 FROM public.admin_users WHERE email = auth.jwt()->>'email')
);

DROP POLICY IF EXISTS "Admin full access on tecnicos" ON public.tecnicos;
CREATE POLICY "Admin full access on tecnicos" ON public.tecnicos FOR ALL USING (
    EXISTS (SELECT 1 FROM public.admin_users WHERE email = auth.jwt()->>'email')
);

-- 6. Insert Initial Tecnicos Data
INSERT INTO public.tecnicos (id, nome, categoria, tipo, descricao, telefone, email, lat, lng, vendedor_parceiro) VALUES
(1, 'PRP_BOSCH_UNIDIESEL (CAMPINAS - SP) REDE PLUS', 'REDE PLUS', 'Fixo', 'ESTOQUE AVANÇADO', '(83) 99101-1964', 'unidiesel.campinas@uol.com.br', -22.8527552, -47.1576292, NULL),
(2, 'PRP_BOSCH_BOMBAS DIESEL (ANÁPOLIS-GO) REDE PLUS', 'REDE PLUS', 'Fixo', 'ESTOQUE AVANÇADO', '(83) 99101-1964', 'bdaestoque@gmail.com', -16.3700681, -48.9407047, NULL),
(3, 'PRP_ALTA PERFORMANCE PNEUS (DUQUE DE CAXIAS-RJ) REDE PLUS', 'REDE PLUS', 'Fixo', 'ESTOQUE AVANÇADO', '(83) 99101-1964', 'faturamento@altaperformancerj.com.br', -22.7543606, -43.2878252, NULL),
(4, 'PRP_SOROCAP PNEUS (BARUERI-SP) REDE PLUS  (EM ESPERA)', 'REDE PLUS', 'Fixo', 'ESTOQUE AVANÇADO', '(83) 99101-1964', 'sp@sorocap.com.br', -23.5203283, -46.9103512, NULL),
(5, 'PRP_HANNOVER PNEUS JOHN BOYD (CAMPINAS-SP) REDE PLUS', 'REDE PLUS', 'Fixo', 'ESTOQUE AVANÇADO', '(83) 99101-1964', 'truck@hannoverpneus.com.br', -22.9337155, -47.1307834, NULL),
(6, 'PRP_APOLOTECH PNEUS (MOGI DAS CRUZES – SP) REDE PLUS', 'REDE PLUS', 'Fixo', 'ESTOQUE AVANÇADO', '(83) 99101-1964', 'fernando.otavio@budini.com', -23.5299389, -46.2189188, NULL),
(7, 'PRP_BOSCH_STARTE DIESEL (FEIRA DE SANTANA-BA) REDE PLUS #EM ESPERA#', 'REDE PLUS', 'Fixo', 'ESTOQUE AVANÇADO', '(83) 99101-1964', 'comercial@mecanicabosch.com.br', -12.231659, -38.9674215, NULL),
(8, 'PRP_SOROCAP PNEUS MATRIZ (SOROCABA-SP) REDE PLUS', 'REDE PLUS', 'Fixo', 'ESTOQUE AVANÇADO', '(83) 99101-1964', 'crenata@sorocap.com.br', -23.5341299, -47.485598, NULL),
(9, 'ATA811_ALEXSANDRO IPLA (JABOATAO DOS GUARARAPES - PE)', 'PSO C/ESTOQUE AVANÇADO', 'Volante', 'ESTOQUE AVANÇADO', '81 8885-9346', 'alexsandro.ipla@omnilink.com.br', -8.1503945, -34.9792711, NULL),
(10, 'PSO_TECNOSUL SOLUCOES EM RASTREAMENTO LTDA (PASSO FUNDO - RS)', 'PSO C/ESTOQUE AVANÇADO', 'Fixo', '(54) 99683-7653 MAURICIO JOSE FERREIRA', '(54) 99683-7653', 'mauriciopfferreira@gmail.com', -28.2714745, -52.416904, NULL),
(11, 'PSO_G6 RASTREADORES (CUBATAO - SP)', 'PSO C/ESTOQUE AVANÇADO', 'Fixo', 'Principal     (13) 99655-4442', '(13) 99655-4442', 'G6rastreadores@gmail.com', -23.8795023, -46.4162192, NULL),
(12, 'SPOT_MTRACKER MOZARLANDIA (MOZARLANDIA - GO)', 'PSO C/ESTOQUE AVANÇADO', 'Fixo', 'ESTOQUE AVANÇADO', '(62) 992165133', 'mtrackertecnologia@outlook.com', -14.7598559, -50.5373436, 'Mikaely da Silva Goncalves'),
(13, 'ATA1110_JOAQUIM HELIO DA SILVA (SÃO PAULO -SP)', 'PSO C/ESTOQUE AVANÇADO', 'Fixo', 'ESTOQUE AVANÇADO', '(11) 94048-8317', 'joaquim.silva@omnilink.com.br', -23.6264413, -46.5856859, NULL),
(14, 'SPOT_MTRACKER CONFRESA (CONFRESA - MT)', 'PSO C/ESTOQUE AVANÇADO', 'Volante', 'ESTOQUE AVANÇADO', '(62) 992165133', 'mtrackertecnologiacfs@outlook.com', -10.6502953, -51.5651787, 'Luana Xavier de Pontes'),
(15, 'ATA614_DENIVALDO RIBEIRO DA SILVA (BRASILIA - DF)', 'PSO C/ESTOQUE AVANÇADO', 'Fixo', 'ESTOQUE AVANÇADO', '(61) 99676-8223', 'denivaldo.silva@omnilink.com.br', -15.8477474, -47.9728284, NULL),
(16, 'PSO_GNM EXATA SERVICOS AUTOMOTIVOS LTDA (SAO PAULO-SP)', 'PSO C/ESTOQUE AVANÇADO', 'Volante', 'ESTOQUE AVANÇADO', '(11) 94781-8416', 'exatatelecom@msn.com', -23.6397507, -46.6039133, 'Lavinia de Oliveira Cavalcante'),
(17, 'ATA1117_RAFAEL PAULINO DA SILVA (SÃO PAULO-SP)', 'PSO C/ESTOQUE AVANÇADO', 'Volante', 'ESTOQUE AVANÇADO', '(11) 99895 2500', 'rafael.paulino@omnilink.com.br', -23.5100622, -46.419522, NULL),
(18, 'PSO_INFRATEC SOLUCOES LTDA (JACAREI - SP)', 'PSO C/ESTOQUE AVANÇADO', 'Fixo', 'ESTOQUE AVANÇADO', '(11) 94288-6463', 'universorastreadoressp@gmail.com', -23.2611777, -45.9525742, 'Valderly Trajano de Morais'),
(19, 'PSO_JUNIOR SILVANO FELISBERTO (TUBARAO - SC)', 'PSO C/ESTOQUE AVANÇADO', 'Fixo', 'ESTOQUE AVANÇADO', '(48) 99117-7234', 'jamtubaraosc@hotmail.com', -28.4893852, -49.0056221, NULL),
(20, 'ATA119_ALEXSANDRO CARDOSO DA SILVA (MONTE MOR - SP)', 'PSO C/ESTOQUE AVANÇADO', 'Volante', 'ESTOQUE AVANÇADO', '17 99659-5317', 'alexsandro.cardoso@omnilink.com.br', -22.9154972, -47.2470454, NULL),
(21, 'PSO_IMPACTO SERVICOS AUTOMOTIVOS LTDA (GUARULHOS - SP)', 'PSO C/ESTOQUE AVANÇADO', 'Volante', 'ESTOQUE AVANÇADO', '(11) 98904-2964', 'adm@impactoaudiocar.com.br', -23.4867341, -46.5461047, 'Maria da Guia da Silva Goncalves'),
(22, 'PSO_MARTA MARIA BATISTA LOPES DOS SANTOS (LINS - SP)', 'PSO C/ESTOQUE AVANÇADO', '', 'ESTOQUE AVANÇADO', '(14) 99682-7056', 'autotechlins@gmail.com', -21.690981, -49.739571, 'Maria Yonara Santos da Silva'),
(23, 'ATA766_PEDRO PAULO DA FONSECA BASTOS (FEIRA DE SANTANA - BA)', 'PSO C/ESTOQUE AVANÇADO', 'VOLANTE', 'ESTOQUE AVANÇADO', '71) 9677-9324', 'pedro.bastos2@omnilink.com.br', -12.2589932, -38.9726203, NULL),
(24, 'PSO_FRANKLIN CLAUDIO DA SILVA FREITAS (SÃO JOSE DO RIBAMAR-MA)', 'PSO C/ESTOQUE AVANÇADO', 'VOLANTE', 'ESTOQUE AVANÇADO', '(98) 98501-9480', 'frankfurt1883@gmail.com', -2.5135693, -44.1944485, 'Valderly Trajano de Morais'),
(25, 'PSO_CONTROL (CAMPINAS - SP)', 'PSO C/ESTOQUE AVANÇADO', '', 'ESTOQUE AVANÇADO', '(19) 97115-0159', 'controllsolution@outlook.com', -22.9589237, -47.0952385, NULL),
(26, 'PSO_KR CRONOTACOGRAFOS (GUARULHOS - SP)', 'PSO C/ESTOQUE AVANÇADO', 'FIXO', 'ESTOQUE AVANÇADO', '(11) 91559-0251', 'KRRASTREADOR@GMAIL.COM', -23.4218411, -46.4278517, 'Nathan Carvalho da Silva'),
(27, 'PSO_MEGA TEC COMERCIO DE INSTRUMENTOS DE PRECISAO LTDA (OSASCO - SP)', 'PSO C/ESTOQUE AVANÇADO', 'Fixo', 'ESTOQUE AVANÇADO', '(11)947578638', 'vilanildo.vdo@gmail.com', -23.5084632, -46.7515897, 'Nathan Carvalho da Silva'),
(28, 'PSO_TORK CRONOTACOGRAFOS (SAO PAULO - SP)', 'PSO C/ESTOQUE AVANÇADO', 'Volante', 'ESTOQUE AVANÇADO', '(11) 99689-2112', 'caroline@torkcronotacografos.com.br', -23.5213926, -46.5692198, 'Maria da Guia da Silva Goncalves'),
(29, 'PSO_RIBERSAT RASTREADORES E AUTO ELETRO LTDA (RIBEIRAO PRETO - SP)', 'PSO C/ESTOQUE AVANÇADO', '', 'ESTOQUE AVANÇADO', '(16) 98262-1564', 'ribersat@yahoo.com', -21.1242109, -47.7728317, NULL),
(30, 'ATA101_ITALO DO NASCIMENTO MENDES (SANTO ANDRE - SP)', 'PSO C/ESTOQUE AVANÇADO', 'Volante', 'ESTOQUE AVANÇADO', '(11) 93386-2454', 'italo.mendes@omnilink.com.br', -23.6693498, -46.5451452, NULL),
(31, 'ATA1112_HALISON PEDRO DA SILVA (SÃO PAULO-SP)', 'PSO C/ESTOQUE AVANÇADO', 'Fixo', 'ESTOQUE AVANÇADO', '(11)96927-5786', 'halison.silva@omnilink.com.br', -23.4657177, -46.6753345, NULL),
(32, 'PSO_NOGUEIRA RASTREADORES E ELETRICA AUTOMOTIVA LTDA (PIRACICABA - SP)', 'PSO C/ESTOQUE AVANÇADO', '', 'ESTOQUE AVANÇADO', '(19) 97403-7581', 'joao@nogueirarastreadores.com.br', -22.6441657, -47.6933944, 'Lavinia de Oliveira Cavalcante'),
(33, 'PSO_ANB TECNOLOGIA (CAMPINAS -SP)', 'PSO C/ESTOQUE AVANÇADO', 'Volante', 'ESTOQUE AVANÇADO', '(19) 99105-0974', 'anbtecnologia@outlook.com', -22.9440142, -47.0847837, 'Maria Heloisa Gomes Albino'),
(34, 'ATA192_RUBENS OLIVEIRA (CAMPINAS – SP)', 'PSO C/ESTOQUE AVANÇADO', 'Fixo', 'ESTOQUE AVANÇADO', '(19) 99321-4222', 'rubens.filho@omnilink.com.br', -22.96335, -47.139175, NULL),
(35, 'PSO_ ANDREY MICHALOVSKI LOCATELLI (VIDEIRA - SC)', 'PSO C/ESTOQUE AVANÇADO', 'Fixo', 'ESTOQUE AVANÇADO', '(49) 99909-5268', 'andreymichalovski@gmail.com', -26.9992613, -51.1570651, 'Valderly Trajano de Morais'),
(36, 'PSO_MILENA DUTRA DE MATTOS (PORTÃO - RS)', 'PSO C/ESTOQUE AVANÇADO', 'Fixo', 'ESTOQUE AVANÇADO', '(51) 98169-7098', 'mmservicosilimitados@gmail.com', -29.6988969, -51.2187206, NULL),
(37, 'SPOT_EDLANGELO PAULINO DOS SANTOS (NOSSA SENHORA DO SOCORRO - SE)', 'PSO C/ESTOQUE AVANÇADO', 'Volante', 'ESTOQUE AVANÇADO', '(79) 8820-1134', 'angeloequipadora@gmail.com', -10.8569724, -37.0828492, 'Lavinia de Oliveira Cavalcante'),
(38, 'PSO_AUTO ELETRICA BELCHIOR LTDA ME (NAVEGANTES - SC)', 'PSO C/ESTOQUE AVANÇADO', 'Fixo', 'ESTOQUE AVANÇADO', '(47) 98449-6620', 'autoeletricabelchior@gmail.com', -26.8310218, -48.6322351, 'Valderly Trajano de Morais'),
(39, 'PSO_ADAIR ANTONIO FIDELES CHAGA - (CHAPECO - SC)', 'PSO C/ESTOQUE AVANÇADO', 'Fixo', 'ESTOQUE AVANÇADO', '(49) 9906-4447', 'adairplayboi747@gmail.com', -27.1045923, -52.6784599, 'Valderly Trajano de Morais'),
(40, 'PSO_ELEN CRISTINE NUNES (DOIS VIZINHOS - PR)', 'PSO C/ESTOQUE AVANÇADO', 'Fixo', 'ESTOQUE AVANÇADO', '(46) 99921-7378', 'rastlog@hotmail.com', -25.7630335, -53.0654063, 'Valderly Trajano de Morais'),
(41, 'ATA114_SINVAL LIMA (SAO PAULO - SP)', 'PSO C/ESTOQUE AVANÇADO', 'Fixo', 'ESTOQUE AVANÇADO', '(11) 98227-0835', 'sinval.lima@omnilink.com.br', -23.5124503, -46.6901855, NULL),
(42, 'PSO_CARLOS RICARDO LIMA DE SOUZA (VOLTA REDONDA -RJ)', 'PSO C/ESTOQUE AVANÇADO', 'Volante', 'ESTOQUE AVANÇADO', '(24) 99932-9824', 'Carlosriicardo@Gmail.Com', -22.4839232, -44.0795474, NULL),
(43, 'PSO_ FILIAL - RASTERSUL (TOLEDO - PR)', 'PSO C/ESTOQUE AVANÇADO', 'Volante', 'ESTOQUE AVANÇADO', '41 999368516', 'rastersulcascavel@gmail.com', -24.7371131, -53.7553987, NULL),
(44, 'PSO_ALEXIA GOULART (CURITIBA - PR)', 'PSO C/ESTOQUE AVANÇADO', '', 'ESTOQUE AVANÇADO', '(41) 98427-0774', 't.hyago@hotmail.com', -25.5566822, -49.2927838, 'Valderly Trajano de Morais'),
(45, 'PSO_DSF REPARACAO E MANUTENCAO LTDA (DUQUE DE CAXIAS -RJ)', 'PSO C/ESTOQUE AVANÇADO', 'Fixo', 'ESTOQUE AVANÇADO', '(21) 97018-4683', '', -22.6788866, -43.3002308, 'Maria da Guia da Silva Goncalves'),
(46, 'PSO_VANGUARD AUTOMOTIVOS (TERESINA - PI)', 'PSO C/ESTOQUE AVANÇADO', 'Fixo', 'ESTOQUE AVANÇADO', '86 98867-6816', 'vanguard.rastreadores@gmail.com', -5.12301, -42.7958248, 'Beatriz'),
(47, 'PSO_FERNANDA FREITAS SILAVA (UBERLANDIA-MG)', 'PSO C/ESTOQUE AVANÇADO', 'Fixo', 'ESTOQUE AVANÇADO', '(34) 991357730', 'waengenhariarenovavel@gmail.com', -18.8560658, -48.2707397, NULL),
(48, 'ATA545_THIAGO RIGO FERRARO (GRAVATAÍ-RS)', 'PSO C/ESTOQUE AVANÇADO', 'Volante', 'ESTOQUE AVANÇADO', '(51) 99207-2166', 'thiago.ferraro@omnilink.com.br', -29.9150925, -51.0621549, NULL),
(49, 'PSO_RICARDO BORGES DA COSTA (CURITIBA - PR)', 'PSO C/ESTOQUE AVANÇADO', 'Volante', 'ESTOQUE AVANÇADO', '(41)99577-9904', 'rp.rastreamentos@gmail.com', -25.4695855, -49.1992518, 'Myllena da Silva Santos'),
(50, 'ATA216_EDSON BONFIM DOS SANTOS (DUQUE DE CAXIAS-RJ)', 'PSO C/ESTOQUE AVANÇADO', 'Fixo', 'ESTOQUE AVANÇADO', '27 99204-1007', 'edson.santos@omnilink.com.br', -22.7518215, -43.2957697, NULL),
(51, 'PSO_MANUTENSAT RASTREAMENTO E MANUTENCAO DE VEICULOS LTDA (JABOATAO DOS GUARARAPES-PE)', 'PSO C/ESTOQUE AVANÇADO', 'Fixo', 'ESTOQUE AVANÇADO', '81991961879', 'manutensatadm@gmail.com', -8.152741, -34.9583333, 'Maria da Guia da Silva Goncalves'),
(52, 'PSO_RASTREAR SAT (APARECIDA DE GOIÂNIA-GO)', 'PSO C/ESTOQUE AVANÇADO', 'Fixo', 'ESTOQUE AVANÇADO', '(62) 98196-0089', 'rastrearsatgyn@gmail.com', -16.7777074, -49.2957417, 'Maria Yonara Santos da Silva'),
(53, 'ATA218_ ARTHUR INACIO DA SILVA (DUQUE DE CAXIAS - RJ)', 'PSO C/ESTOQUE AVANÇADO', 'Fixo', '(21) 97472-6459 ARTHUR INACIO', '(21) 97472-6459', 'arthur.inacio@omnilink.com.br', -22.6244771, -43.2200625, NULL),
(54, 'PSO_RASTER SUL (CURITIBA - PR)', 'PSO C/ESTOQUE AVANÇADO', 'Fixo', 'ESTOQUE AVANÇADO', '(41) 99699-1992', 'rastersul@gmail.com', -25.5846747, -49.314565, NULL),
(55, 'PSO_START TEC RASTREADORES LTDA (CUIABA-MT)', 'PSO C/ESTOQUE AVANÇADO', 'Volante', 'ESTOQUE AVANÇADO', '65 98158-1111', 'startecrastreadores@gmail.com', -15.6737646, -56.0415273, NULL),
(56, 'PSO_LD RASTREAMENTO (CAMPO GRANDE - MS)', 'PSO C/ESTOQUE AVANÇADO', 'Fixo', 'ESTOQUE AVANÇADO', '(67) 99119-8863', 'ldrastreamento2022@gmail.com', -20.5215484, -54.5877036, NULL),
(57, 'ATA215_GILMAR DA APARECIDA IBA (SÃO JOÃO DE MERITI - RJ)', 'PSO C/ESTOQUE AVANÇADO', 'Fixo', 'ESTOQUE AVANÇADO', '(19) 99404-7768', 'gilmar.iba@omnilink.com.br', -22.8056161, -43.3889824, NULL),
(58, 'PSO_SOLUTECH ASSISTENCIA TECNICA (CASTANHAL-PA)', 'PSO C/ESTOQUE AVANÇADO', 'Volante', 'ESTOQUE AVANÇADO', '(94) 99103-7317', 'Solutechassistenciatecnica9@gmail.com', -1.2922861, -47.9460126, 'Lavinia de Oliveira Cavalcante'),
(59, 'PSO_RICARDO RASTREADORES LTDA (BETIM - MG)', 'PSO C/ESTOQUE AVANÇADO', '', 'PSO_RICARDO RASTREADORES LTDA (BETIM - MG)', '(31) 99118-4581', 'ricardo@ricardorastreadores.com.br', -19.9608227, -44.0755592, 'Mikaely da Silva Goncalves'),
(60, 'PSO_JAMIKLELSE LACERDA LOPES (GOIANIA-GO)', 'PSO C/ESTOQUE AVANÇADO', 'Volante', 'ESTOQUE AVANÇADO', '(62) 99138-0144', 'klelse.gyn@gmail.com', -16.586088, -49.3406695, 'Maria Yonara Santos da Silva'),
(61, 'PSO_RODRIGUES AUTO ELÉTRICA (VITÓRIA-ES)', 'PSO C/ESTOQUE AVANÇADO', 'Volante', 'ESTOQUE AVANÇADO', '(27) 98877-5020', '', -20.2782351, -40.3314066, 'Nathan'),
(62, 'PSO_ERSAT SOLUÇÕES E RASTREAMENTOS', 'PSO C/ESTOQUE AVANÇADO', 'Fixo', 'ESTOQUE AVANÇADO', '(11)97688-2186', 'gisele.vidal@ersat.com.br', -23.5028205, -46.6859433, 'Kauanne Soares da Silva Januário'),
(63, 'PSO_BH RASTREAR (BELO HORIZONTE - MG)', 'PSO C/ESTOQUE AVANÇADO', 'Fixo', 'ESTOQUE AVANÇADO', '(31) 98455-7326', 'ritabhmg@gmail.com', -19.9191203, -43.999407, 'Maria Heloisa Gomes Albino'),
(64, 'ATA314_CLAYTON FRANCISCO OLIVEIRA MORAES (BELO HORIZONTE - MG)', 'PSO C/ESTOQUE AVANÇADO', 'Fixo', '(31) 9102-1096 - CLAYTON FRANCISCO', '(31) 9102-1096', 'clayton.moraes@omnilink.com.br', -19.8278766, -43.9892726, NULL),
(65, 'PSO_ANDERLAN GONCALVES BRITO - FORSEG SOLUCOES (EUSEBIO-CE)', 'PSO C/ESTOQUE AVANÇADO', 'Volante', 'ESTOQUE AVANÇADO', '(85) 98709-7000', 'forseg.solucoes@gmail.com', -3.912493, -38.450145, 'Maria da Guia da Silva Goncalves'),
(66, 'PSO_A.C COUTINHO SAT (LAURO DE FREITAS-BA)', 'PSO C/ESTOQUE AVANÇADO', 'Volante', 'ESTOQUE AVANÇADO', '(71)992517778', 'tl_sat@hotmail.com', -12.876345, -38.2993595, 'Kauanne Soares da Silva Januário'),
(67, 'ATA211_EDVALDO FERREIRA (CAXIAS-RJ)', 'PSO C/ESTOQUE AVANÇADO', 'Fixo', 'ESTOQUE AVANÇADO', '(21) 98103-7021', '', -22.7879121, -43.3222978, NULL),
(68, 'SPOT_SUELTON ALVES LOPES DOS SANTOS (SENADOR CANEGO - GO)', 'PSO C/ESTOQUE AVANÇADO', 'Volante', 'ESTOQUE AVANÇADO', '(62) 9368-4229', 'sueltt01@gmail.com', -16.662115, -49.1627482, NULL),
(69, 'PSO_UNITY SERVICOS (DUQUE DE CAXIAS - RJ)', 'PSO C/ESTOQUE AVANÇADO', '', 'ESTOQUE AVANÇADO', '(21) 97903-9685', 'unity.rastreadores@gmail.com', -22.7908334, -43.2872833, NULL),
(70, 'PSO_MARQUINHOS MANUTENCOES (SÃO LUDGERO - SC)', 'PSO C/ESTOQUE AVANÇADO', 'Fixo', 'ESTOQUE AVANÇADO', '(48) 99683-1862', 'marquinhosmanutencaoeletricas@gmail.com', -28.332181, -49.1820549, NULL),
(71, 'PSO_DIEGO DE OLIVEIRA SANTOS (CARAPICUIBA - SP)', 'PSO C/ESTOQUE AVANÇADO', '', 'Volante', '(11)94928-8334', 'diegorastreador104@gmail.com', -23.5524143, -46.8316578, 'Maria Yonara Santos da Silva'),
(72, 'PSO_HEITOR DOS REIS ARAUJO (APARECIDA DE GOIANIA -GO)', 'PSO C/ESTOQUE AVANÇADO', 'Volante', 'ESTOQUE AVANÇADO', '(62) 98623-5979', 'heitordosreis1996@gmail.com', -16.8399354, -49.2442712, 'Mikaely da Silva Goncalves'),
(73, 'PSO_BRASIL SAT RASTREADORES (FEIRA DE SANTANA - BA) -ESTOQUE AVANÇADO', 'PSO C/ESTOQUE AVANÇADO', 'Fixo', '', '(75) 99260-1574', 'brasilsat1@gmail.com', -12.241091, -38.983035, NULL),
(74, 'ATA1116_JOSE VINÍCIUS FRANÇA BEZERRA (DIADEMA-SP)', 'PSO C/ESTOQUE AVANÇADO', 'Fixo', '', '(11) 93275-9031', 'jose.bezerra@omnilink.com.br', -23.6806974, -46.5967546, NULL),
(75, 'PSO_JRF SERVICOS (LONDRINA - PR)', 'PSO C/ESTOQUE AVANÇADO', 'Fixo', 'ESTOQUE AVANÇADO', '(43) 99916-2325', 'jrfservicoautomotivo@gmail.com', -23.2986963, -51.1489652, 'Valderly Trajano de Morais'),
(76, 'ATA_912 ALESSANDRO DE SOUZA CONCEIÇÃO', 'PSO C/ESTOQUE AVANÇADO', 'Volante', 'ESTOQUE AVANÇADO', '91 8184-2932', 'alessandro.conceicao@omnilink.com.br', -1.4055609, -48.395663, NULL),
(77, 'PSO_LUNA NASCIMENTO DA SILVA (MANAUS-AM)', 'PSO C/ESTOQUE AVANÇADO', 'Volante', 'ESTOQUE AVANÇADO', '(92) 98473-2115', 'edson.veras2013@gmail.com', -3.0101821, -59.9665022, NULL),
(78, 'PSO_MRG RASTREADORES LTDA (MANDAGUACU - PR)', 'PSO C/ESTOQUE AVANÇADO', '', 'ESTOQUE AVANÇADO', '(44) 98806-7889', 'raulazevedo2708@gmail.com', -23.3371728, -52.0884266, NULL),
(79, 'ATA JOAO PAULO PARPINELLI DA SILVA (CURITIBA - PR)', 'ATA', 'Volante', '(41) 99103-5086 JOÃO', '(41) 99103-5086', 'joao.silva@omnilink.com.br', -25.4001516, -49.1967725, NULL),
(80, 'ATA979_THIAGO NEGRIS (MS - CAMPO GRANDE)', 'ATA', '', 'V- Volante', '(67) 99268-7445', 'thiago.negris@omnilink.com.br', -20.4273914, -54.6054224, NULL),
(81, 'ATA_HEITOR FERNANDES (VITORIA - ES)', 'ATA', 'Volante', '', '27 99909-3652', 'heitor.rodrigues@omnilink.com.br', -20.2593734, -40.2642661, NULL),
(82, 'ATA111_ANTHONY FELISBINO RIBEIRO SANTANA (EMBU DAS ARTES - SP)', 'ATA', 'Volante', 'ESTOQUE AVANÇADO', '11 93263-8781', 'anthony.santana@omnilink.com.br', -23.6609413, -46.8039174, NULL),
(83, 'ATA981_RICARDO MAIA FRANCA (SAO LUIS - MA)', 'ATA', 'VOLANTE', '', '(98) 81315633', 'ricardo.franca@omnilink.com.br', -2.5077371, -44.051062, NULL),
(84, 'PSO_RTS RASTREAMENTO LTDA (SERRA - ES)', 'PSO', 'Fixo', '', '27 99665-0036', 'rts.comerciales@gmail.com', -20.173796, -40.200513, 'Myllena da Silva Santos'),
(85, 'PSO_SCA SILVA (BARRA MANSA - RJ)', 'PSO', 'Volante', '', '(21) 99837-6226', 'scadiretoria@scasilva.com.br', -22.560478, -44.1412159, NULL),
(86, 'PSO_EDSON CARLOS MARTINS (URUGUAIANA - RS)', 'PSO', 'Fixo', '55 99936-8153 EDSON CARLOS MARTINS', '55 99936-8153', 'edsonmartins864201@gmail.com', -29.7797112, -57.0810189, NULL),
(87, 'PSO_WAGNER DAVI GOETTEMS (VIDEIRA - SC)', 'PSO', 'Fixo', '', '(46) 99907-0162', 'wagnergoettems@gmail.com', -26.9979996, -51.151239, NULL),
(88, 'PSO_PEDRO BROZEGHINI (CARIACICA - ES)', 'PSO', 'Volante', '(27) 9 9807-4114 - POLIANA', '9807-4114', 'vixtracker@gmail.com', -20.3553154, -40.3897578, NULL),
(89, 'PSO_CLOVIS FABRICIO DOS SANTOS BARBOSA (RIBEIRAO PRETO - SP)', 'PSO', 'Volante', '', '(16) 99251-7654', 'contato.worldservice@gmail.com', -21.2067333, -47.5974126, NULL),
(90, 'PSO_LUCAS BRESSA COMELLI (VOTORANTIM - SP)', 'PSO', '', '', '(15) 99636-7465', 'lucas.comelli@hotmail.com', -23.5448963, -47.4563094, NULL),
(91, 'PSO_4 RODAS AUTO CENTER LTDA (JUIZ DE FORA - MG)', 'PSO', 'Fixo', '', '(32) 9839-4142', 'autocenter.alfenas@outlook.com', -21.7060906, -43.4263527, 'Nathan'),
(92, 'PSO_APARECIDA MARIA DE CARVALHO RIBEIRO (BELO HORIZONTE - MG)', 'PSO', 'Fixo', '', '(31) 99518-1432', 'adenilsonronibeiro3@gmail.com', -19.8263775, -43.9304165, NULL),
(93, 'PSO_BIRASAT SOLUCOES (SC - ITAJAI)', 'PSO', 'Fixo', '+55 47 9700-6604 - Ubiraci', '47 9700-6604', 'financeirobirasat@gmail.com', -26.8385161, -48.7139504, NULL),
(94, 'PSO_LUANA BRESSAN DUARTE (ELOI MENDES - MG)', 'PSO', 'Fixo', '', '(35) 99189-8939', 'luanabressanduarte@gmail.com', -21.6042314, -45.5511859, 'Valderly Trajano de Morais'),
(95, 'PSO_SDTRACKERS LTDA (RONDONOPOLIS - MT)', 'PSO', 'Fixo', '', '66 992088919', 'Sdrastreadores@gmail.com', -16.4714539, -54.5610573, NULL),
(96, 'PSO_WESLEYJAN LACERDA LOPES (ANAPOLIS-GO)', 'PSO', 'Volante', '', '62 99138-0144', 'jamiklelselacerda@gmail.com', -16.3812949, -48.965204, 'Maria Yonara Santos da Silva'),
(97, 'PSO_VIETECH DAVIDSON DANILO VIEIRA (MONTES CLAROS - MG)', 'PSO', '', 'Volante', '38 99801-2689', 'vietechrastreadores@hotmail.com', -16.6854174, -43.8771733, NULL),
(98, 'PSO_AUTOTECH SOLUCOES TECNOLOGICAS (PARAUAPEBAS-PA)', 'PSO', 'Volante', '', '(94) 98804-8353', 'portelaesilva.tec@gmail.com', -6.0404491, -49.8903411, NULL),
(99, 'PSO_DIOGO ROBERTO LOPES DOS SANTOS (FEIRA DE SANTANA - BA)', 'PSO', 'Fixo', '', '75 99223-7611', 'DIOGOELETROSERV@YAHOO.COM.BR', -12.2388849, -38.9820047, 'Maria Yonara Santos da Silva'),
(100, 'PSO_ELTON MACEDO SERVICOS (MACEIO-AL)', 'PSO', 'Fixo', 'upervisor: (81) 9205-7944 Marcus Cordeiro Leal', '(82) 99909-6907', 'elton-marcolino@hotmail.com', -9.5420775, -35.7259741, 'Kauanne Soares da Silva Januário'),
(101, 'PSO_LIMA RASTREADORES (VITORIA DA CONQUISTA - BA)', 'PSO', 'Volante', '', '(77) 9952-5604', 'lima.rastreadores230591@gmail.com', -14.8296966, -40.8778049, 'Mikaely da Silva Goncalves'),
(102, 'PSO_MICHELLINE RAMOS DO NASCIMENTO (SAO CAITANO -PE)', 'PSO', 'Volante', '', '(81) 98144-2407', 'michellineramos@hotmail.com', -8.3198465, -36.1343869, 'maria yonara Santos da Silva'),
(103, 'PSO_THYSCIANE DE ALMEIDA (FORTALEZA - CE)', 'PSO', 'Volante', '', '(85) 98961-1354', 'ELETROSAT.CONT@GMAIL.COM', -3.8503958, -38.5170546, 'Maria Yonara Santos da Silva'),
(104, 'PSO_AMIZAEL INSTALACOES (CAXIAS DO SUL - RS)', 'PSO', 'Volante', '54984038275', '54984038275', 'amizaelgps@outlook.com', -29.1648618, -51.209, NULL),
(105, 'PSO_BRENDA RENATA DA SILVA (CUIABA-MT)', 'PSO', 'Volante', 'PSO_BRENDA RENATA DA SILVA (CUIABA-MT)', '(65) 99230-9727', 'reb.rastreadores@gmail.com', -15.6345241, -55.9522642, NULL),
(106, 'PSO_MOOBI RASTREAMENTO (SORRISO - MT)', 'PSO', 'Volante', '', '66 992576389', 'moobirastreamento@autlook.com', -12.5867927, -55.7491303, NULL),
(107, 'PSO_ALTO TIETE TRUCK CENTER LTDA (MOGI DAS CRUZES – SP)', 'PSO', 'Fixo', '', '(11) 94778 2276', 'jonas@truckcenteraltotiete.com.br', -23.5453352, -46.2502705, 'Lavinia de Oliveira Cavalcante'),
(108, 'PSO_DARIO GOMES (CURVELO MG)', 'PSO', 'FIXO', 'Contato: (11) 93017-8212 - DARIO', '(11) 93017-8212', 'Santosgomes1418@gmail.com', -18.7869994, -44.4501153, NULL),
(109, 'PSO_ZAYON RASTREAMENTO (RIO BRANCO - AC)', 'PSO', 'Volante', '', '(68) 99227-2025', 'lucas33lopes@gmail.com', -9.9703238, -67.8370054, NULL),
(110, 'SPOT_EVANDRO SOUZA MASCARENHAS (SÃO PAULO - SP)', 'SPOT', 'Volante', 'Volante Telefone: (11) 96314-4268 - Evandro', '(11) 96314-4268', 'esmevandro@yahoo.com.br', -23.5495043, -46.4500716, NULL),
(111, 'SPOT_STARTRACKCONECT (BAURU - SP)', 'SPOT', 'Volante', '', '14 98183-9053', 'startrack01@yahoo.com.br', -22.3110001, -49.078016, 'Maria Yonara Santos da Silva'),
(112, 'SPOT_PAULO HENRIQUE DA SILVA DE SOUZA (BARREIRAS - BA)', 'SPOT', 'Volante', '', '(77) 99985-0089', 'phsilvasouza1997@gmail.com', -12.1477407, -44.9743569, 'Mikaely da Silva Goncalves'),
(113, 'SPOT_K.A.B AUTO ELETRICA DOURADO MS LTDA (DOURADOS - MS)', 'SPOT', 'Fixo', '', '996650-8161', 'kauebaptista9@gmail.com', -22.2193511, -54.6842206, NULL),
(114, 'SPOT_LEANDRO RUI (VILHENA - RO )', 'SPOT', 'Volante', '', '(69) 9282-1161', 'LEANDROVHA157@GMAIL.COM', -12.7138868, -60.1398217, NULL),
(115, 'SPOT_GABRIEL FERREIRA (TRES LAGOAS - MS)', 'SPOT', 'Fixo', '', '(67) 99247-3530', 'leonardoff740@gmail.com', -20.8111989, -51.720619, NULL),
(116, 'SPOT_M.J.L DA SILVA (MACAPÁ - AP)', 'SPOT', 'Volante', '', '(96) 99167-5157', 'saomiguel1.mj@hotmail.com', 0.0248765, -51.0695031, NULL),
(117, 'SPOT_BALSAS GPS RASTREAMENTO (BALSAS - MA)', 'SPOT', 'Volante', '', '(99) 999874017', 'balsasgps@gmail.com', -7.5438961, -46.0744462, NULL),
(118, 'SPOT_TECHNOHALL ELETRICA (TIMOTEO - MG)', 'SPOT', '', 'FX - Fixo', '(31) 993386673', 'technohalleletrica@gmail.com', -19.5291173, -42.6596144, NULL),
(119, 'SPOT_MAGNU RASTREAMENTO (BOA VISTA - RR)', 'SPOT', 'Volante', '', '(95) 98420-8840', 'elieziomeireles2@gmail.com', 2.8029042, -60.7067478, NULL),
(120, 'SPOT_MULTSAT COMERCIO E SERVICOS (CABO DE SANTO AGOSTINHO - PE)', 'SPOT', 'Fixo', '', '(81) 99646-2001', 'Contato.multsat@hotmail.com', -8.2982245, -35.0214953, NULL),
(121, 'SPOT_THIAGO DA SILVA (ARAGUAINA - TO)', 'SPOT', 'Fixo', '', '63 991049356', 'capturerastreamento@gmail.com', -7.1975351, -48.1944429, NULL),
(122, 'SPOT_JULIANA CORREIA SANTOS (ITABUNA - BA)', 'SPOT', 'Volante', '(73) 98826-4325 LEANDRO', '(73) 98826-4325', 'leoaudiosascar@hotmail.com', -14.8078264, -39.2915263, NULL)
ON CONFLICT (id) DO NOTHING;
SELECT setval('tecnicos_id_seq', (SELECT COALESCE(MAX(id), 0) + 1 FROM public.tecnicos), false);

-- 7. Insert Initial Categories Data
INSERT INTO public.categories (id, name) VALUES
('cat-1', 'Rastreadores Omnilink'),
('cat-2', 'Acessórios & Sensores'),
('cat-3', 'Iscas de Carga (Descartáveis/Recarregáveis)'),
('cat-4', 'Serviços & Licenças')
ON CONFLICT (id) DO NOTHING;

-- 8. Insert Initial Products Data
INSERT INTO public.products (id, category_id, name, description, default_price, pix_price, monthly_fee, image_url, is_active, commercial_rules) VALUES
('prod-1', 'cat-1', 'OMNITURBO (Kit Omniturbo)', 'Equipamento rastreador e controlador de frota Omnilink — OMNITURBO (Kit Omniturbo).', 6930, 6930, 205.86, '/products/prod-img-1.jpg', true, '{"allow_pix":true,"allow_boleto":true,"max_boleto_installments":3,"allow_card":true,"max_card_installments":12,"allow_financing":false}'::jsonb),
('prod-2', 'cat-1', 'OMNIDUAL', 'Equipamento rastreador e controlador de frota Omnilink — OMNIDUAL.', 4830, 4830, 130.6, '/products/prod-img-2.jpg', true, '{"allow_pix":true,"allow_boleto":true,"max_boleto_installments":3,"allow_card":true,"max_card_installments":12,"allow_financing":false}'::jsonb),
('prod-3', 'cat-1', 'OMNICARGA 2G + GPS DESCARTÁVEL', 'Equipamento rastreador e controlador de frota Omnilink — OMNICARGA 2G + GPS DESCARTÁVEL.', 275.25, 275.25, 0, '/products/prod-img-3.jpg', true, '{"allow_pix":true,"allow_boleto":true,"max_boleto_installments":3,"allow_card":true,"max_card_installments":12,"allow_financing":false}'::jsonb),
('prod-4', 'cat-1', 'OMNIMOB - KIT COMPLETO', 'Equipamento rastreador e controlador de frota Omnilink — OMNIMOB - KIT COMPLETO.', 2236.06, 2236.06, 0, '/products/prod-img-4.jpg', true, '{"allow_pix":true,"allow_boleto":true,"max_boleto_installments":3,"allow_card":true,"max_card_installments":12,"allow_financing":false}'::jsonb),
('prod-5', 'cat-1', 'OMNISAFE - DASHCAM 4CH', 'Equipamento rastreador e controlador de frota Omnilink — OMNISAFE - DASHCAM 4CH.', 4189.5, 4189.5, 130, '/products/prod-img-5.jpg', true, '{"allow_pix":true,"allow_boleto":true,"max_boleto_installments":3,"allow_card":true,"max_card_installments":12,"allow_financing":false}'::jsonb),
('prod-6', 'cat-1', 'OMNILORA', 'Equipamento rastreador e controlador de frota Omnilink — OMNILORA.', 756, 756, 20, '/products/prod-img-6.jpg', true, '{"allow_pix":true,"allow_boleto":true,"max_boleto_installments":3,"allow_card":true,"max_card_installments":12,"allow_financing":false}'::jsonb),
('prod-7', 'cat-1', 'OMNIDUAL + OMNILORA', 'Equipamento rastreador e controlador de frota Omnilink — OMNIDUAL + OMNILORA.', 5563.95, 5563.95, 0, '/products/prod-img-7.jpg', true, '{"allow_pix":true,"allow_boleto":true,"max_boleto_installments":3,"allow_card":true,"max_card_installments":12,"allow_financing":false}'::jsonb),
('prod-8', 'cat-1', 'OMNITURBO + OMNILORA', 'Equipamento rastreador e controlador de frota Omnilink — OMNITURBO + OMNILORA.', 7663.95, 7663.95, 0, '/products/prod-img-8.jpg', true, '{"allow_pix":true,"allow_boleto":true,"max_boleto_installments":3,"allow_card":true,"max_card_installments":12,"allow_financing":false}'::jsonb),
('prod-9', 'cat-1', 'OMNICARGA 4G + GPS DESCARTÁVEL', 'Equipamento rastreador e controlador de frota Omnilink — OMNICARGA 4G + GPS DESCARTÁVEL.', 309.75, 309.75, 0, '/products/prod-img-9.jpg', true, '{"allow_pix":true,"allow_boleto":true,"max_boleto_installments":3,"allow_card":true,"max_card_installments":12,"allow_financing":false}'::jsonb),
('prod-10', 'cat-1', 'OMNICARGA 4G + GPS + IMÃ DESCARTÁVEL', 'Equipamento rastreador e controlador de frota Omnilink — OMNICARGA 4G + GPS + IMÃ DESCARTÁVEL.', 309.75, 309.75, 0, '/products/prod-img-10.jpg', true, '{"allow_pix":true,"allow_boleto":true,"max_boleto_installments":3,"allow_card":true,"max_card_installments":12,"allow_financing":false}'::jsonb),
('prod-11', 'cat-1', 'OMNICARGA 2G + GPS + IMÃ DESCARTÁVEL', 'Equipamento rastreador e controlador de frota Omnilink — OMNICARGA 2G + GPS + IMÃ DESCARTÁVEL.', 257.25, 257.25, 0, '/products/prod-img-11.jpg', true, '{"allow_pix":true,"allow_boleto":true,"max_boleto_installments":3,"allow_card":true,"max_card_installments":12,"allow_financing":false}'::jsonb),
('prod-12', 'cat-1', 'OMNICARRETA', 'Equipamento rastreador e controlador de frota Omnilink — OMNICARRETA.', 1260, 1260, 59, '/products/prod-img-12.jpg', true, '{"allow_pix":true,"allow_boleto":true,"max_boleto_installments":3,"allow_card":true,"max_card_installments":12,"allow_financing":false}'::jsonb),
('prod-13', 'cat-1', 'OMNITURBO SEM TECLADO', 'Equipamento rastreador e controlador de frota Omnilink — OMNITURBO SEM TECLADO.', 5880, 5880, 205.86, '/products/prod-img-13.jpg', true, '{"allow_pix":true,"allow_boleto":true,"max_boleto_installments":3,"allow_card":true,"max_card_installments":12,"allow_financing":false}'::jsonb),
('prod-14', 'cat-1', 'OMNIDUAL SEM TECLADO', 'Equipamento rastreador e controlador de frota Omnilink — OMNIDUAL SEM TECLADO.', 3780, 3780, 130.6, '/products/prod-img-14.jpg', true, '{"allow_pix":true,"allow_boleto":true,"max_boleto_installments":3,"allow_card":true,"max_card_installments":12,"allow_financing":false}'::jsonb),
('prod-15', 'cat-1', 'OMNISAFE PLUS MDVR 4CH I.A', 'Equipamento rastreador e controlador de frota Omnilink — OMNISAFE PLUS MDVR 4CH I.A.', 5517.75, 5517.75, 130, '/products/prod-img-15.jpg', true, '{"allow_pix":true,"allow_boleto":true,"max_boleto_installments":3,"allow_card":true,"max_card_installments":12,"allow_financing":false}'::jsonb),
('prod-16', 'cat-1', 'OMNICARGA 4G LORA COM GPS LI0650 DESCARTÁVEL', 'Equipamento rastreador e controlador de frota Omnilink — OMNICARGA 4G LORA COM GPS LI0650 DESCARTÁVEL.', 330.75, 330.75, 0, '/products/prod-img-16.jpg', true, '{"allow_pix":true,"allow_boleto":true,"max_boleto_installments":3,"allow_card":true,"max_card_installments":12,"allow_financing":false}'::jsonb),
('prod-17', 'cat-1', 'OMNICARGA 4G LORA COM GPS LI0650 - RETORNÁVEL', 'Equipamento rastreador e controlador de frota Omnilink — OMNICARGA 4G LORA COM GPS LI0650 - RETORNÁVEL.', 99, 99, 0, '/products/prod-img-17.jpg', true, '{"allow_pix":true,"allow_boleto":true,"max_boleto_installments":3,"allow_card":true,"max_card_installments":12,"allow_financing":false}'::jsonb),
('prod-18', 'cat-1', 'OMNISAFE PLUS MDVR 8CH I.A', 'Equipamento rastreador e controlador de frota Omnilink — OMNISAFE PLUS MDVR 8CH I.A.', 6126.75, 6126.75, 130, '/products/prod-img-18.jpg', true, '{"allow_pix":true,"allow_boleto":true,"max_boleto_installments":3,"allow_card":true,"max_card_installments":12,"allow_financing":false}'::jsonb),
('prod-19', 'cat-1', 'Urbano Omnicarreta', 'Equipamento rastreador e controlador de frota Omnilink — Urbano Omnicarreta.', 474, 474, 0, '/products/prod-img-19.jpg', true, '{"allow_pix":true,"allow_boleto":true,"max_boleto_installments":3,"allow_card":true,"max_card_installments":12,"allow_financing":false}'::jsonb),
('prod-20', 'cat-1', 'OMNICARGA 4G + GPS + IMA RETORNÁVEL 12 meses', 'Equipamento rastreador e controlador de frota Omnilink — OMNICARGA 4G + GPS + IMA RETORNÁVEL 12 meses.', 103.95, 103.95, 0, '/products/prod-img-20.jpg', true, '{"allow_pix":true,"allow_boleto":true,"max_boleto_installments":3,"allow_card":true,"max_card_installments":12,"allow_financing":false}'::jsonb),
('prod-21', 'cat-1', 'OMNICARGA 4G + GPS RETORNAVEL - 12 meses', 'Equipamento rastreador e controlador de frota Omnilink — OMNICARGA 4G + GPS RETORNAVEL - 12 meses.', 103.95, 103.95, 0, '/products/prod-img-21.jpg', true, '{"allow_pix":true,"allow_boleto":true,"max_boleto_installments":3,"allow_card":true,"max_card_installments":12,"allow_financing":false}'::jsonb),
('prod-22', 'cat-1', 'OMNITURBO SEM TECLADO (BAU BLINDADO)', 'Equipamento rastreador e controlador de frota Omnilink — OMNITURBO SEM TECLADO (BAU BLINDADO).', 6762, 6762, 205.86, '/products/prod-img-22.jpg', true, '{"allow_pix":true,"allow_boleto":true,"max_boleto_installments":3,"allow_card":true,"max_card_installments":12,"allow_financing":false}'::jsonb),
('prod-23', 'cat-1', 'OMNICARRETA COM PLACA SOLAR', 'Equipamento rastreador e controlador de frota Omnilink — OMNICARRETA COM PLACA SOLAR.', 1600, 1600, 59, '/products/prod-img-23.jpg', true, '{"allow_pix":true,"allow_boleto":true,"max_boleto_installments":3,"allow_card":true,"max_card_installments":12,"allow_financing":false}'::jsonb),
('prod-24', 'cat-1', 'Pneu Conectado 295/80R22.5 OT321', 'Equipamento rastreador e controlador de frota Omnilink — Pneu Conectado 295/80R22.5 OT321.', 3200, 3200, 0, '/products/prod-img-24.jpg', true, '{"allow_pix":true,"allow_boleto":true,"max_boleto_installments":3,"allow_card":true,"max_card_installments":12,"allow_financing":false}'::jsonb),
('prod-25', 'cat-1', 'OMNITPMS', 'Equipamento rastreador e controlador de frota Omnilink — OMNITPMS.', 990, 990, 0, '/products/prod-img-25.jpg', true, '{"allow_pix":true,"allow_boleto":true,"max_boleto_installments":3,"allow_card":true,"max_card_installments":12,"allow_financing":false}'::jsonb),
('prod-26', 'cat-2', 'TRAVA DE QUINTA RODA E.LOCK', 'Acessório e componente homologado Show Tecnologia / Omnilink — TRAVA DE QUINTA RODA E.LOCK.', 3700, 3700, 0, '/products/prod-img-26.jpg', true, '{"allow_pix":true,"allow_boleto":true,"max_boleto_installments":3,"allow_card":true,"max_card_installments":12,"allow_financing":false}'::jsonb),
('prod-27', 'cat-1', 'OMNICARGA 4G LORA COM GPS COM IMÃ LI0650 DESCARTÁVEL', 'Equipamento rastreador e controlador de frota Omnilink — OMNICARGA 4G LORA COM GPS COM IMÃ LI0650 DESCARTÁVEL.', 330.75, 330.75, 0, '/products/prod-img-27.jpg', true, '{"allow_pix":true,"allow_boleto":true,"max_boleto_installments":3,"allow_card":true,"max_card_installments":12,"allow_financing":false}'::jsonb),
('prod-28', 'cat-1', 'OMNITURBO - LT', 'Equipamento rastreador e controlador de frota Omnilink — OMNITURBO - LT.', 6930, 6930, 205.86, '/products/prod-img-28.jpg', true, '{"allow_pix":true,"allow_boleto":true,"max_boleto_installments":3,"allow_card":true,"max_card_installments":12,"allow_financing":false}'::jsonb),
('prod-29', 'cat-1', 'OMNITURBO - LT SEM TECLADO', 'Equipamento rastreador e controlador de frota Omnilink — OMNITURBO - LT SEM TECLADO.', 5880, 5880, 205.86, '/products/prod-img-29.jpg', true, '{"allow_pix":true,"allow_boleto":true,"max_boleto_installments":3,"allow_card":true,"max_card_installments":12,"allow_financing":false}'::jsonb),
('prod-30', 'cat-1', 'OMNISAFE - DASHCAM 5CH (ADAS + DSM + 1 câm. interna e 2 externas)', 'Equipamento rastreador e controlador de frota Omnilink — OMNISAFE - DASHCAM 5CH (ADAS + DSM + 1 câm. interna e 2 externas).', 6448.53, 6448.53, 0, '/products/prod-img-30.jpg', true, '{"allow_pix":true,"allow_boleto":true,"max_boleto_installments":3,"allow_card":true,"max_card_installments":12,"allow_financing":false}'::jsonb),
('prod-31', 'cat-1', 'OMNISAFE - DASHCAM 5CH (ADAS + DSM)', 'Equipamento rastreador e controlador de frota Omnilink — OMNISAFE - DASHCAM 5CH (ADAS + DSM).', 5094.02, 5094.02, 0, '/products/prod-img-31.jpg', true, '{"allow_pix":true,"allow_boleto":true,"max_boleto_installments":3,"allow_card":true,"max_card_installments":12,"allow_financing":false}'::jsonb),
('prod-32', 'cat-1', 'OMNIDUAL - RI7454 - TESTES', 'Equipamento rastreador e controlador de frota Omnilink — OMNIDUAL - RI7454 - TESTES.', 4830, 4830, 130.6, '/products/prod-img-32.jpg', true, '{"allow_pix":true,"allow_boleto":true,"max_boleto_installments":3,"allow_card":true,"max_card_installments":12,"allow_financing":false}'::jsonb),
('prod-33', 'cat-1', 'OMNITURBO - RI7484 - TESTES', 'Equipamento rastreador e controlador de frota Omnilink — OMNITURBO - RI7484 - TESTES.', 6930, 6930, 205.86, '/products/prod-img-33.jpg', true, '{"allow_pix":true,"allow_boleto":true,"max_boleto_installments":3,"allow_card":true,"max_card_installments":12,"allow_financing":false}'::jsonb),
('prod-34', 'cat-2', 'CJ. CONEXÃO CAVALO (CHICOTE ESPIRAL) P&P', 'Acessório e componente homologado Show Tecnologia / Omnilink — CJ. CONEXÃO CAVALO (CHICOTE ESPIRAL) P&P.', 487.2, 487.2, 0, '/products/prod-img-34.jpg', true, '{"allow_pix":true,"allow_boleto":true,"max_boleto_installments":3,"allow_card":true,"max_card_installments":12,"allow_financing":false}'::jsonb),
('prod-35', 'cat-2', 'TOMADA DE CONEXÃO DE CARRETA P&P', 'Acessório e componente homologado Show Tecnologia / Omnilink — TOMADA DE CONEXÃO DE CARRETA P&P.', 260.4, 260.4, 0, '/products/prod-img-35.jpg', true, '{"allow_pix":true,"allow_boleto":true,"max_boleto_installments":3,"allow_card":true,"max_card_installments":12,"allow_financing":false}'::jsonb),
('prod-36', 'cat-2', 'CJ TRAVA BAÚ - P. TRASEIRA DUPLA', 'Acessório e componente homologado Show Tecnologia / Omnilink — CJ TRAVA BAÚ - P. TRASEIRA DUPLA.', 1504.65, 1504.65, 0, '/products/prod-img-36.jpg', true, '{"allow_pix":true,"allow_boleto":true,"max_boleto_installments":3,"allow_card":true,"max_card_installments":12,"allow_financing":false}'::jsonb),
('prod-37', 'cat-2', 'SENSOR DE ENGATE E DESENGATE ELETRÔNICO', 'Acessório e componente homologado Show Tecnologia / Omnilink — SENSOR DE ENGATE E DESENGATE ELETRÔNICO.', 243.6, 243.6, 0, '/products/prod-img-37.jpg', true, '{"allow_pix":true,"allow_boleto":true,"max_boleto_installments":3,"allow_card":true,"max_card_installments":12,"allow_financing":false}'::jsonb),
('prod-38', 'cat-2', 'CONJUNTO DE SENSOR DE PORTA DE BAÚ', 'Acessório e componente homologado Show Tecnologia / Omnilink — CONJUNTO DE SENSOR DE PORTA DE BAÚ.', 408.45, 408.45, 0, '/products/prod-img-38.jpg', true, '{"allow_pix":true,"allow_boleto":true,"max_boleto_installments":3,"allow_card":true,"max_card_installments":12,"allow_financing":false}'::jsonb),
('prod-39', 'cat-2', 'CONJUNTO DE SENSOR DE PORTA DE BAÚ ADICIONAL', 'Acessório e componente homologado Show Tecnologia / Omnilink — CONJUNTO DE SENSOR DE PORTA DE BAÚ ADICIONAL.', 408.45, 408.45, 0, '/products/prod-img-39.jpg', true, '{"allow_pix":true,"allow_boleto":true,"max_boleto_installments":3,"allow_card":true,"max_card_installments":12,"allow_financing":false}'::jsonb),
('prod-40', 'cat-2', 'CJ TRAVA CARRETA FRIGORÍFICA - P. TRASEIRA', 'Acessório e componente homologado Show Tecnologia / Omnilink — CJ TRAVA CARRETA FRIGORÍFICA - P. TRASEIRA.', 1871.1, 1871.1, 0, '/products/prod-img-40.jpg', true, '{"allow_pix":true,"allow_boleto":true,"max_boleto_installments":3,"allow_card":true,"max_card_installments":12,"allow_financing":false}'::jsonb),
('prod-41', 'cat-2', 'CJ TRAVA CARRETA - P. TRASEIRA ROLL UP', 'Acessório e componente homologado Show Tecnologia / Omnilink — CJ TRAVA CARRETA - P. TRASEIRA ROLL UP.', 1304.1, 1304.1, 0, '/products/prod-img-41.jpg', true, '{"allow_pix":true,"allow_boleto":true,"max_boleto_installments":3,"allow_card":true,"max_card_installments":12,"allow_financing":false}'::jsonb),
('prod-42', 'cat-2', 'CJ TRAVA BAÚ - P. TRASEIRA ROLL UP', 'Acessório e componente homologado Show Tecnologia / Omnilink — CJ TRAVA BAÚ - P. TRASEIRA ROLL UP.', 1462.65, 1462.65, 0, '/products/prod-img-42.jpg', true, '{"allow_pix":true,"allow_boleto":true,"max_boleto_installments":3,"allow_card":true,"max_card_installments":12,"allow_financing":false}'::jsonb),
('prod-43', 'cat-2', 'CJ TRAVA BAÚ - P. LATERAL', 'Acessório e componente homologado Show Tecnologia / Omnilink — CJ TRAVA BAÚ - P. LATERAL.', 1554, 1554, 0, '/products/prod-img-43.jpg', true, '{"allow_pix":true,"allow_boleto":true,"max_boleto_installments":3,"allow_card":true,"max_card_installments":12,"allow_financing":false}'::jsonb),
('prod-44', 'cat-2', 'CJ - SENSOR DE TEMPERATURA INOX ADICIONAL', 'Acessório e componente homologado Show Tecnologia / Omnilink — CJ - SENSOR DE TEMPERATURA INOX ADICIONAL.', 475, 475, 0, '/products/prod-img-44.jpg', true, '{"allow_pix":true,"allow_boleto":true,"max_boleto_installments":3,"allow_card":true,"max_card_installments":12,"allow_financing":false}'::jsonb),
('prod-45', 'cat-2', 'CJ TRAVA ELETROMAG. VAN - P. LATERAL', 'Acessório e componente homologado Show Tecnologia / Omnilink — CJ TRAVA ELETROMAG. VAN - P. LATERAL.', 1000.65, 1000.65, 0, '/products/prod-img-45.jpg', true, '{"allow_pix":true,"allow_boleto":true,"max_boleto_installments":3,"allow_card":true,"max_card_installments":12,"allow_financing":false}'::jsonb),
('prod-46', 'cat-2', 'CJ TRAVA BAÚ - P. TRASEIRA PLATAFORMA', 'Acessório e componente homologado Show Tecnologia / Omnilink — CJ TRAVA BAÚ - P. TRASEIRA PLATAFORMA.', 1748.25, 1748.25, 0, '/products/prod-img-46.jpg', true, '{"allow_pix":true,"allow_boleto":true,"max_boleto_installments":3,"allow_card":true,"max_card_installments":12,"allow_financing":false}'::jsonb),
('prod-47', 'cat-2', 'CABO ADAPTADOR TERMINAL 5020', 'Acessório e componente homologado Show Tecnologia / Omnilink — CABO ADAPTADOR TERMINAL 5020.', 15.75, 15.75, 0, '/products/prod-img-47.jpg', true, '{"allow_pix":true,"allow_boleto":true,"max_boleto_installments":3,"allow_card":true,"max_card_installments":12,"allow_financing":false}'::jsonb),
('prod-48', 'cat-2', 'ARIETE DA QUINTA RODA JOST', 'Acessório e componente homologado Show Tecnologia / Omnilink — ARIETE DA QUINTA RODA JOST.', 291.9, 291.9, 0, '/products/prod-img-48.jpg', true, '{"allow_pix":true,"allow_boleto":true,"max_boleto_installments":3,"allow_card":true,"max_card_installments":12,"allow_financing":false}'::jsonb),
('prod-49', 'cat-2', 'ARIETE DA QUINTA RODA FONTAINE', 'Acessório e componente homologado Show Tecnologia / Omnilink — ARIETE DA QUINTA RODA FONTAINE.', 316.05, 316.05, 0, '/products/prod-img-49.jpg', true, '{"allow_pix":true,"allow_boleto":true,"max_boleto_installments":3,"allow_card":true,"max_card_installments":12,"allow_financing":false}'::jsonb),
('prod-50', 'cat-2', 'TRAVA QUINTA RODA HÍBRIDA JOST/FONTAINE - 24V', 'Acessório e componente homologado Show Tecnologia / Omnilink — TRAVA QUINTA RODA HÍBRIDA JOST/FONTAINE - 24V.', 1278.9, 1278.9, 0, '/products/prod-img-50.jpg', true, '{"allow_pix":true,"allow_boleto":true,"max_boleto_installments":3,"allow_card":true,"max_card_installments":12,"allow_financing":false}'::jsonb),
('prod-51', 'cat-2', 'ADESIVO LATERAL OMNILINK 215X265MM', 'Acessório e componente homologado Show Tecnologia / Omnilink — ADESIVO LATERAL OMNILINK 215X265MM.', 6, 6, 0, '/products/prod-img-51.jpg', true, '{"allow_pix":true,"allow_boleto":true,"max_boleto_installments":3,"allow_card":true,"max_card_installments":12,"allow_financing":false}'::jsonb),
('prod-52', 'cat-2', 'BATENTE CANTONEIRA', 'Acessório e componente homologado Show Tecnologia / Omnilink — BATENTE CANTONEIRA.', 27, 27, 0, '/products/prod-img-52.jpg', true, '{"allow_pix":true,"allow_boleto":true,"max_boleto_installments":3,"allow_card":true,"max_card_installments":12,"allow_financing":false}'::jsonb),
('prod-53', 'cat-2', 'BATENTE CANTONEIRA - MP - CJ TE', 'Acessório e componente homologado Show Tecnologia / Omnilink — BATENTE CANTONEIRA - MP - CJ TE.', 27, 27, 0, '/products/prod-img-53.jpg', true, '{"allow_pix":true,"allow_boleto":true,"max_boleto_installments":3,"allow_card":true,"max_card_installments":12,"allow_financing":false}'::jsonb),
('prod-54', 'cat-2', 'BATENTE DE ENCAIXE MT PEQ', 'Acessório e componente homologado Show Tecnologia / Omnilink — BATENTE DE ENCAIXE MT PEQ.', 29, 29, 0, '/products/prod-img-54.jpg', true, '{"allow_pix":true,"allow_boleto":true,"max_boleto_installments":3,"allow_card":true,"max_card_installments":12,"allow_financing":false}'::jsonb),
('prod-55', 'cat-2', 'BATENTE DE ENCAIXE MT PEQ - MP', 'Acessório e componente homologado Show Tecnologia / Omnilink — BATENTE DE ENCAIXE MT PEQ - MP.', 86, 86, 0, '/products/prod-img-55.jpg', true, '{"allow_pix":true,"allow_boleto":true,"max_boleto_installments":3,"allow_card":true,"max_card_installments":12,"allow_financing":false}'::jsonb),
('prod-56', 'cat-2', 'BATENTE PL CORRER SPRINTER', 'Acessório e componente homologado Show Tecnologia / Omnilink — BATENTE PL CORRER SPRINTER.', 130, 130, 0, '/products/prod-img-56.jpg', true, '{"allow_pix":true,"allow_boleto":true,"max_boleto_installments":3,"allow_card":true,"max_card_installments":12,"allow_financing":false}'::jsonb),
('prod-57', 'cat-2', 'BATENTE UNIVERSAL - MP - CJ TE', 'Acessório e componente homologado Show Tecnologia / Omnilink — BATENTE UNIVERSAL - MP - CJ TE.', 43, 43, 0, '/products/prod-img-57.jpg', true, '{"allow_pix":true,"allow_boleto":true,"max_boleto_installments":3,"allow_card":true,"max_card_installments":12,"allow_financing":false}'::jsonb),
('prod-58', 'cat-2', 'CJ - SENSOR DE TEMPERATURA INOX', 'Acessório e componente homologado Show Tecnologia / Omnilink — CJ - SENSOR DE TEMPERATURA INOX.', 408.45, 408.45, 0, '/products/prod-img-58.jpg', true, '{"allow_pix":true,"allow_boleto":true,"max_boleto_installments":3,"allow_card":true,"max_card_installments":12,"allow_financing":false}'::jsonb),
('prod-59', 'cat-2', 'BLOQUEADOR TIPO 1 FULL-RANGE', 'Acessório e componente homologado Show Tecnologia / Omnilink — BLOQUEADOR TIPO 1 FULL-RANGE.', 521.85, 521.85, 0, '/products/prod-img-59.jpg', true, '{"allow_pix":true,"allow_boleto":true,"max_boleto_installments":3,"allow_card":true,"max_card_installments":12,"allow_financing":false}'::jsonb),
('prod-60', 'cat-2', 'CJ MULTI SENSOR DE UMIDADE + TEMPERATURA C/ CERTIFICADO', 'Acessório e componente homologado Show Tecnologia / Omnilink — CJ MULTI SENSOR DE UMIDADE + TEMPERATURA C/ CERTIFICADO.', 1347.15, 1347.15, 0, '/products/prod-img-60.jpg', true, '{"allow_pix":true,"allow_boleto":true,"max_boleto_installments":3,"allow_card":true,"max_card_installments":12,"allow_financing":false}'::jsonb),
('prod-61', 'cat-2', 'CONJUNTO 02 SENSORES DE PAINEL', 'Acessório e componente homologado Show Tecnologia / Omnilink — CONJUNTO 02 SENSORES DE PAINEL.', 164.85, 164.85, 0, '/products/prod-img-61.jpg', true, '{"allow_pix":true,"allow_boleto":true,"max_boleto_installments":3,"allow_card":true,"max_card_installments":12,"allow_financing":false}'::jsonb),
('prod-62', 'cat-2', 'CJ SENSOR ADICIONAL PORTA DE BAÚ', 'Acessório e componente homologado Show Tecnologia / Omnilink — CJ SENSOR ADICIONAL PORTA DE BAÚ.', 371.55, 371.55, 0, '/products/prod-img-62.jpg', true, '{"allow_pix":true,"allow_boleto":true,"max_boleto_installments":3,"allow_card":true,"max_card_installments":12,"allow_financing":false}'::jsonb),
('prod-63', 'cat-2', 'CJ SENSOR DE TEMPERATURA INOX C/ CERTIFICADO', 'Acessório e componente homologado Show Tecnologia / Omnilink — CJ SENSOR DE TEMPERATURA INOX C/ CERTIFICADO.', 731.1, 731.1, 0, '/products/prod-img-63.jpg', true, '{"allow_pix":true,"allow_boleto":true,"max_boleto_installments":3,"allow_card":true,"max_card_installments":12,"allow_financing":false}'::jsonb),
('prod-64', 'cat-2', 'CJ MULTI SENSOR DE UMIDADE + TEMPERATURA', 'Acessório e componente homologado Show Tecnologia / Omnilink — CJ MULTI SENSOR DE UMIDADE + TEMPERATURA.', 1116.15, 1116.15, 0, '/products/prod-img-64.jpg', true, '{"allow_pix":true,"allow_boleto":true,"max_boleto_installments":3,"allow_card":true,"max_card_installments":12,"allow_financing":false}'::jsonb),
('prod-65', 'cat-2', 'CJ SENSOR DE UMIDADE + TEMPERATURA', 'Acessório e componente homologado Show Tecnologia / Omnilink — CJ SENSOR DE UMIDADE + TEMPERATURA.', 1283, 1283, 0, '/products/prod-img-65.jpg', true, '{"allow_pix":true,"allow_boleto":true,"max_boleto_installments":3,"allow_card":true,"max_card_installments":12,"allow_financing":false}'::jsonb),
('prod-66', 'cat-2', 'CJ TRAVA CARRETA - P. TRASEIRA DUPLA', 'Acessório e componente homologado Show Tecnologia / Omnilink — CJ TRAVA CARRETA - P. TRASEIRA DUPLA.', 1504.65, 1504.65, 0, '/products/prod-img-66.jpg', true, '{"allow_pix":true,"allow_boleto":true,"max_boleto_installments":3,"allow_card":true,"max_card_installments":12,"allow_financing":false}'::jsonb),
('prod-67', 'cat-2', 'CJ TRAVA ELETROMAG. VAN - P. TRASEIRA', 'Acessório e componente homologado Show Tecnologia / Omnilink — CJ TRAVA ELETROMAG. VAN - P. TRASEIRA.', 1040.55, 1040.55, 0, '/products/prod-img-67.jpg', true, '{"allow_pix":true,"allow_boleto":true,"max_boleto_installments":3,"allow_card":true,"max_card_installments":12,"allow_financing":false}'::jsonb),
('prod-68', 'cat-2', 'CJ ACIONAMENTO TRAVA MOTORIZADA INOX', 'Acessório e componente homologado Show Tecnologia / Omnilink — CJ ACIONAMENTO TRAVA MOTORIZADA INOX.', 661.5, 661.5, 0, '/products/prod-img-68.jpg', true, '{"allow_pix":true,"allow_boleto":true,"max_boleto_installments":3,"allow_card":true,"max_card_installments":12,"allow_financing":false}'::jsonb),
('prod-69', 'cat-2', 'CHICOTE RELE ACIONAMENTO ESPECIAL', 'Acessório e componente homologado Show Tecnologia / Omnilink — CHICOTE RELE ACIONAMENTO ESPECIAL.', 280.35, 280.35, 0, '/products/prod-img-69.jpg', true, '{"allow_pix":true,"allow_boleto":true,"max_boleto_installments":3,"allow_card":true,"max_card_installments":12,"allow_financing":false}'::jsonb),
('prod-70', 'cat-2', 'BOTÃO TRAVA DE BAÚ', 'Acessório e componente homologado Show Tecnologia / Omnilink — BOTÃO TRAVA DE BAÚ.', 92.4, 92.4, 0, '/products/prod-img-70.jpg', true, '{"allow_pix":true,"allow_boleto":true,"max_boleto_installments":3,"allow_card":true,"max_card_installments":12,"allow_financing":false}'::jsonb),
('prod-71', 'cat-2', 'SUPORTE TRAVA DE SOBREPOR', 'Acessório e componente homologado Show Tecnologia / Omnilink — SUPORTE TRAVA DE SOBREPOR.', 39, 39, 0, '/products/prod-img-71.jpg', true, '{"allow_pix":true,"allow_boleto":true,"max_boleto_installments":3,"allow_card":true,"max_card_installments":12,"allow_financing":false}'::jsonb),
('prod-72', 'cat-2', 'SUPORTE TRAVA DE SOBREPOR - MP - CJ TE', 'Acessório e componente homologado Show Tecnologia / Omnilink — SUPORTE TRAVA DE SOBREPOR - MP - CJ TE.', 59, 59, 0, '/products/prod-img-72.jpg', true, '{"allow_pix":true,"allow_boleto":true,"max_boleto_installments":3,"allow_card":true,"max_card_installments":12,"allow_financing":false}'::jsonb),
('prod-73', 'cat-2', 'TAMPA CX TRAVA ELETROMAG. (CJ)', 'Acessório e componente homologado Show Tecnologia / Omnilink — TAMPA CX TRAVA ELETROMAG. (CJ).', 38, 38, 0, '/products/prod-img-73.jpg', true, '{"allow_pix":true,"allow_boleto":true,"max_boleto_installments":3,"allow_card":true,"max_card_installments":12,"allow_financing":false}'::jsonb),
('prod-74', 'cat-2', 'TAMPA SUPORTE TRAVA SOBREPOR - MP - CJ TE', 'Acessório e componente homologado Show Tecnologia / Omnilink — TAMPA SUPORTE TRAVA SOBREPOR - MP - CJ TE.', 27, 27, 0, '/products/prod-img-74.jpg', true, '{"allow_pix":true,"allow_boleto":true,"max_boleto_installments":3,"allow_card":true,"max_card_installments":12,"allow_financing":false}'::jsonb),
('prod-75', 'cat-2', 'BASE DE REFORÇO PL SPRINTER', 'Acessório e componente homologado Show Tecnologia / Omnilink — BASE DE REFORÇO PL SPRINTER.', 18, 18, 0, '/products/prod-img-75.jpg', true, '{"allow_pix":true,"allow_boleto":true,"max_boleto_installments":3,"allow_card":true,"max_card_installments":12,"allow_financing":false}'::jsonb),
('prod-76', 'cat-2', 'BASE REFORÇO MOT PEQ PORTA BAÚ - MP - CJ', 'Acessório e componente homologado Show Tecnologia / Omnilink — BASE REFORÇO MOT PEQ PORTA BAÚ - MP - CJ.', 86, 86, 0, '/products/prod-img-76.jpg', true, '{"allow_pix":true,"allow_boleto":true,"max_boleto_installments":3,"allow_card":true,"max_card_installments":12,"allow_financing":false}'::jsonb),
('prod-77', 'cat-2', 'BASE REFORÇO PORTA BAÚ MOTORIZADA - MP - CJ TM', 'Acessório e componente homologado Show Tecnologia / Omnilink — BASE REFORÇO PORTA BAÚ MOTORIZADA - MP - CJ TM.', 86, 86, 0, '/products/prod-img-77.jpg', true, '{"allow_pix":true,"allow_boleto":true,"max_boleto_installments":3,"allow_card":true,"max_card_installments":12,"allow_financing":false}'::jsonb),
('prod-78', 'cat-2', 'BASE REFORÇO PORTA BAÚ SOLENOIDE - MP - CJ TE', 'Acessório e componente homologado Show Tecnologia / Omnilink — BASE REFORÇO PORTA BAÚ SOLENOIDE - MP - CJ TE.', 49, 49, 0, '/products/prod-img-78.jpg', true, '{"allow_pix":true,"allow_boleto":true,"max_boleto_installments":3,"allow_card":true,"max_card_installments":12,"allow_financing":false}'::jsonb),
('prod-79', 'cat-2', 'CX TRAVA ELETROMAGNETICA (CJ)', 'Acessório e componente homologado Show Tecnologia / Omnilink — CX TRAVA ELETROMAGNETICA (CJ).', 85.05, 85.05, 0, '/products/prod-img-79.jpg', true, '{"allow_pix":true,"allow_boleto":true,"max_boleto_installments":3,"allow_card":true,"max_card_installments":12,"allow_financing":false}'::jsonb),
('prod-80', 'cat-2', 'ESPAÇADOR DE TRAVA BAÚ ORIGINAL (213X170X10)', 'Acessório e componente homologado Show Tecnologia / Omnilink — ESPAÇADOR DE TRAVA BAÚ ORIGINAL (213X170X10).', 86, 86, 0, '/products/prod-img-80.jpg', true, '{"allow_pix":true,"allow_boleto":true,"max_boleto_installments":3,"allow_card":true,"max_card_installments":12,"allow_financing":false}'::jsonb),
('prod-81', 'cat-2', 'ESPAÇADOR DE TRAVA BAÚ ORIGINAL (213X170X15)', 'Acessório e componente homologado Show Tecnologia / Omnilink — ESPAÇADOR DE TRAVA BAÚ ORIGINAL (213X170X15).', 86, 86, 0, '/products/prod-img-81.jpg', true, '{"allow_pix":true,"allow_boleto":true,"max_boleto_installments":3,"allow_card":true,"max_card_installments":12,"allow_financing":false}'::jsonb),
('prod-82', 'cat-2', 'ESPAÇADOR DE TRAVA BAÚ ORIGINAL (213X170X25)', 'Acessório e componente homologado Show Tecnologia / Omnilink — ESPAÇADOR DE TRAVA BAÚ ORIGINAL (213X170X25).', 58, 58, 0, '/products/prod-img-82.jpg', true, '{"allow_pix":true,"allow_boleto":true,"max_boleto_installments":3,"allow_card":true,"max_card_installments":12,"allow_financing":false}'::jsonb),
('prod-83', 'cat-2', 'TRAVA MOTORIZADA UNIVERSAL PEQ. CONTR. INTERN', 'Acessório e componente homologado Show Tecnologia / Omnilink — TRAVA MOTORIZADA UNIVERSAL PEQ. CONTR. INTERN.', 683.55, 683.55, 0, '/products/prod-img-83.jpg', true, '{"allow_pix":true,"allow_boleto":true,"max_boleto_installments":3,"allow_card":true,"max_card_installments":12,"allow_financing":false}'::jsonb),
('prod-84', 'cat-2', 'TRAVA ELETROMAGNETICA BIVOLT', 'Acessório e componente homologado Show Tecnologia / Omnilink — TRAVA ELETROMAGNETICA BIVOLT.', 862.05, 862.05, 0, '/products/prod-img-84.jpg', true, '{"allow_pix":true,"allow_boleto":true,"max_boleto_installments":3,"allow_card":true,"max_card_installments":12,"allow_financing":false}'::jsonb),
('prod-85', 'cat-2', 'CJ BLOQUEADOR DE COMBUSTIVEL STANDARD', 'Acessório e componente homologado Show Tecnologia / Omnilink — CJ BLOQUEADOR DE COMBUSTIVEL STANDARD.', 847.35, 847.35, 0, '/products/prod-img-85.jpg', true, '{"allow_pix":true,"allow_boleto":true,"max_boleto_installments":3,"allow_card":true,"max_card_installments":12,"allow_financing":false}'::jsonb),
('prod-86', 'cat-2', 'MÓDULO DE COMUNICAÇÃO 4G (MODULO SOMENTE 44XX)', 'Acessório e componente homologado Show Tecnologia / Omnilink — MÓDULO DE COMUNICAÇÃO 4G (MODULO SOMENTE 44XX).', 2800, 2800, 0, '/products/prod-img-86.jpg', true, '{"allow_pix":true,"allow_boleto":true,"max_boleto_installments":3,"allow_card":true,"max_card_installments":12,"allow_financing":false}'::jsonb),
('prod-87', 'cat-2', 'ANTENA SATELITE', 'Acessório e componente homologado Show Tecnologia / Omnilink — ANTENA SATELITE.', 3061.8, 3061.8, 0, '/products/prod-img-87.jpg', true, '{"allow_pix":true,"allow_boleto":true,"max_boleto_installments":3,"allow_card":true,"max_card_installments":12,"allow_financing":false}'::jsonb),
('prod-88', 'cat-2', 'TECLADO TVC200', 'Acessório e componente homologado Show Tecnologia / Omnilink — TECLADO TVC200.', 1050, 1050, 0, '/products/prod-img-88.jpg', true, '{"allow_pix":true,"allow_boleto":true,"max_boleto_installments":3,"allow_card":true,"max_card_installments":12,"allow_financing":false}'::jsonb),
('prod-89', 'cat-2', 'SUPORTE TERM ALFANUMERICO 5020', 'Acessório e componente homologado Show Tecnologia / Omnilink — SUPORTE TERM ALFANUMERICO 5020.', 139.65, 139.65, 0, '/products/prod-img-1.jpg', true, '{"allow_pix":true,"allow_boleto":true,"max_boleto_installments":3,"allow_card":true,"max_card_installments":12,"allow_financing":false}'::jsonb),
('prod-90', 'cat-2', 'CAMERA EXTERNA DASHCAM 720P OMNI-ES-WB720ES', 'Acessório e componente homologado Show Tecnologia / Omnilink — CAMERA EXTERNA DASHCAM 720P OMNI-ES-WB720ES.', 249.38, 249.38, 0, '/products/prod-img-2.jpg', true, '{"allow_pix":true,"allow_boleto":true,"max_boleto_installments":3,"allow_card":true,"max_card_installments":12,"allow_financing":false}'::jsonb),
('prod-91', 'cat-2', 'CABO EXTENSOR PARA CAMERAS OMNISAFE BLINDADO 8MT', 'Acessório e componente homologado Show Tecnologia / Omnilink — CABO EXTENSOR PARA CAMERAS OMNISAFE BLINDADO 8MT.', 136.5, 136.5, 0, '/products/prod-img-3.jpg', true, '{"allow_pix":true,"allow_boleto":true,"max_boleto_installments":3,"allow_card":true,"max_card_installments":12,"allow_financing":false}'::jsonb),
('prod-92', 'cat-2', 'CABO EXTENSOR PARA CAMERAS OMNISAFE BLINDADO 5MT', 'Acessório e componente homologado Show Tecnologia / Omnilink — CABO EXTENSOR PARA CAMERAS OMNISAFE BLINDADO 5MT.', 115.5, 115.5, 0, '/products/prod-img-4.jpg', true, '{"allow_pix":true,"allow_boleto":true,"max_boleto_installments":3,"allow_card":true,"max_card_installments":12,"allow_financing":false}'::jsonb),
('prod-93', 'cat-2', 'CAMERA INTERNA MDVR 720P Omni-RM-WP720RM', 'Acessório e componente homologado Show Tecnologia / Omnilink — CAMERA INTERNA MDVR 720P Omni-RM-WP720RM.', 236.25, 236.25, 0, '/products/prod-img-5.jpg', true, '{"allow_pix":true,"allow_boleto":true,"max_boleto_installments":3,"allow_card":true,"max_card_installments":12,"allow_financing":false}'::jsonb),
('prod-94', 'cat-2', 'CAMERA INTERNA DASHCAM 720P OMNI-RM-WP720RM', 'Acessório e componente homologado Show Tecnologia / Omnilink — CAMERA INTERNA DASHCAM 720P OMNI-RM-WP720RM.', 236.25, 236.25, 0, '/products/prod-img-6.jpg', true, '{"allow_pix":true,"allow_boleto":true,"max_boleto_installments":3,"allow_card":true,"max_card_installments":12,"allow_financing":false}'::jsonb),
('prod-95', 'cat-2', 'CAMERA INTERNA MDVR 1080P Omni-RM-WP1080RM', 'Acessório e componente homologado Show Tecnologia / Omnilink — CAMERA INTERNA MDVR 1080P Omni-RM-WP1080RM.', 404.25, 404.25, 0, '/products/prod-img-7.jpg', true, '{"allow_pix":true,"allow_boleto":true,"max_boleto_installments":3,"allow_card":true,"max_card_installments":12,"allow_financing":false}'::jsonb),
('prod-96', 'cat-2', 'CHICOTE INSTALACAO PADRAO RI4450ME/MM', 'Acessório e componente homologado Show Tecnologia / Omnilink — CHICOTE INSTALACAO PADRAO RI4450ME/MM.', 400, 400, 0, '/products/prod-img-8.jpg', true, '{"allow_pix":true,"allow_boleto":true,"max_boleto_installments":3,"allow_card":true,"max_card_installments":12,"allow_financing":false}'::jsonb),
('prod-97', 'cat-2', 'TERMINAL ALFANUMERICO 5020 (CINZA)', 'Acessório e componente homologado Show Tecnologia / Omnilink — TERMINAL ALFANUMERICO 5020 (CINZA).', 1275.75, 1275.75, 0, '/products/prod-img-9.jpg', true, '{"allow_pix":true,"allow_boleto":true,"max_boleto_installments":3,"allow_card":true,"max_card_installments":12,"allow_financing":false}'::jsonb),
('prod-98', 'cat-2', 'SENSOR DE PORTA MAGNÉTICO INVISIVEL (UNIDADE)', 'Acessório e componente homologado Show Tecnologia / Omnilink — SENSOR DE PORTA MAGNÉTICO INVISIVEL (UNIDADE).', 47.25, 47.25, 0, '/products/prod-img-10.jpg', true, '{"allow_pix":true,"allow_boleto":true,"max_boleto_installments":3,"allow_card":true,"max_card_installments":12,"allow_financing":false}'::jsonb),
('prod-99', 'cat-2', 'SENSOR DE TEMPERATURA C/ 3 FIOS DE 15M', 'Acessório e componente homologado Show Tecnologia / Omnilink — SENSOR DE TEMPERATURA C/ 3 FIOS DE 15M.', 270, 270, 0, '/products/prod-img-11.jpg', true, '{"allow_pix":true,"allow_boleto":true,"max_boleto_installments":3,"allow_card":true,"max_card_installments":12,"allow_financing":false}'::jsonb),
('prod-100', 'cat-2', 'RELE AUXILIAR NA/NF 12V', 'Acessório e componente homologado Show Tecnologia / Omnilink — RELE AUXILIAR NA/NF 12V.', 39, 39, 0, '/products/prod-img-12.jpg', true, '{"allow_pix":true,"allow_boleto":true,"max_boleto_installments":3,"allow_card":true,"max_card_installments":12,"allow_financing":false}'::jsonb),
('prod-101', 'cat-2', 'PERFIL U 15X57 PVC SEMI-RIGIDO (1M)', 'Acessório e componente homologado Show Tecnologia / Omnilink — PERFIL U 15X57 PVC SEMI-RIGIDO (1M).', 12.6, 12.6, 0, '/products/prod-img-13.jpg', true, '{"allow_pix":true,"allow_boleto":true,"max_boleto_installments":3,"allow_card":true,"max_card_installments":12,"allow_financing":false}'::jsonb),
('prod-102', 'cat-2', 'SUPORTE RELE DUPLO DIODO COM FUSIVEL 15A', 'Acessório e componente homologado Show Tecnologia / Omnilink — SUPORTE RELE DUPLO DIODO COM FUSIVEL 15A.', 19.95, 19.95, 0, '/products/prod-img-14.jpg', true, '{"allow_pix":true,"allow_boleto":true,"max_boleto_installments":3,"allow_card":true,"max_card_installments":12,"allow_financing":false}'::jsonb),
('prod-103', 'cat-2', 'KIT BLOQUEIO OMNISAFE', 'Acessório e componente homologado Show Tecnologia / Omnilink — KIT BLOQUEIO OMNISAFE.', 324, 324, 0, '/products/prod-img-15.jpg', true, '{"allow_pix":true,"allow_boleto":true,"max_boleto_installments":3,"allow_card":true,"max_card_installments":12,"allow_financing":false}'::jsonb),
('prod-104', 'cat-2', 'DASHCAM 4H I.A.', 'Acessório e componente homologado Show Tecnologia / Omnilink — DASHCAM 4H I.A..', 4074, 4074, 130, '/products/prod-img-16.jpg', true, '{"allow_pix":true,"allow_boleto":true,"max_boleto_installments":3,"allow_card":true,"max_card_installments":12,"allow_financing":false}'::jsonb),
('prod-105', 'cat-2', 'CAMERA EXTERNA MDVR 1080P Omni-ES-WB1080ES', 'Acessório e componente homologado Show Tecnologia / Omnilink — CAMERA EXTERNA MDVR 1080P Omni-ES-WB1080ES.', 420, 420, 0, '/products/prod-img-17.jpg', true, '{"allow_pix":true,"allow_boleto":true,"max_boleto_installments":3,"allow_card":true,"max_card_installments":12,"allow_financing":false}'::jsonb),
('prod-106', 'cat-2', 'CAMERA INTERNA MDVR 1080P Omni-RM-WP1080RM', 'Acessório e componente homologado Show Tecnologia / Omnilink — CAMERA INTERNA MDVR 1080P Omni-RM-WP1080RM.', 410, 410, 0, '/products/prod-img-18.jpg', true, '{"allow_pix":true,"allow_boleto":true,"max_boleto_installments":3,"allow_card":true,"max_card_installments":12,"allow_financing":false}'::jsonb),
('prod-107', 'cat-2', 'CAMERA INTERNA DASHCAM 720P OMNI-RM-WP720RM', 'Acessório e componente homologado Show Tecnologia / Omnilink — CAMERA INTERNA DASHCAM 720P OMNI-RM-WP720RM.', 236.25, 236.25, 0, '/products/prod-img-19.jpg', true, '{"allow_pix":true,"allow_boleto":true,"max_boleto_installments":3,"allow_card":true,"max_card_installments":12,"allow_financing":false}'::jsonb),
('prod-108', 'cat-2', 'MNT – MODULO DASHCAM T5504', 'Acessório e componente homologado Show Tecnologia / Omnilink — MNT – MODULO DASHCAM T5504.', 1900, 1900, 0, '/products/prod-img-20.jpg', true, '{"allow_pix":true,"allow_boleto":true,"max_boleto_installments":3,"allow_card":true,"max_card_installments":12,"allow_financing":false}'::jsonb),
('prod-109', 'cat-2', 'CONJUNTO CAVALO CARRETA OMNISAFE 4 CAMERAS', 'Acessório e componente homologado Show Tecnologia / Omnilink — CONJUNTO CAVALO CARRETA OMNISAFE 4 CAMERAS.', 816.9, 816.9, 0, '/products/prod-img-21.jpg', true, '{"allow_pix":true,"allow_boleto":true,"max_boleto_installments":3,"allow_card":true,"max_card_installments":12,"allow_financing":false}'::jsonb),
('prod-110', 'cat-2', 'MONITOR INTERNO OMNISAFE MDVR 7 POLEGADAS', 'Acessório e componente homologado Show Tecnologia / Omnilink — MONITOR INTERNO OMNISAFE MDVR 7 POLEGADAS.', 684, 684, 0, '/products/prod-img-22.jpg', true, '{"allow_pix":true,"allow_boleto":true,"max_boleto_installments":3,"allow_card":true,"max_card_installments":12,"allow_financing":false}'::jsonb),
('prod-111', 'cat-2', 'CHICOTE ESP. SEN. CARRETA (CJ)', 'Acessório e componente homologado Show Tecnologia / Omnilink — CHICOTE ESP. SEN. CARRETA (CJ).', 469.35, 469.35, 0, '/products/prod-img-23.jpg', true, '{"allow_pix":true,"allow_boleto":true,"max_boleto_installments":3,"allow_card":true,"max_card_installments":12,"allow_financing":false}'::jsonb),
('prod-112', 'cat-2', 'SIRENE BI-VOLT (120 DB - 6 TONS)', 'Acessório e componente homologado Show Tecnologia / Omnilink — SIRENE BI-VOLT (120 DB - 6 TONS).', 43.05, 43.05, 0, '/products/prod-img-24.jpg', true, '{"allow_pix":true,"allow_boleto":true,"max_boleto_installments":3,"allow_card":true,"max_card_installments":12,"allow_financing":false}'::jsonb),
('prod-113', 'cat-2', 'SENSOR PORTA CAB. MAG. POL. INVERTIDA', 'Acessório e componente homologado Show Tecnologia / Omnilink — SENSOR PORTA CAB. MAG. POL. INVERTIDA.', 85.05, 85.05, 0, '/products/prod-img-25.jpg', true, '{"allow_pix":true,"allow_boleto":true,"max_boleto_installments":3,"allow_card":true,"max_card_installments":12,"allow_financing":false}'::jsonb),
('prod-114', 'cat-2', 'OMNISAFE - SENSOR DE BAFOMETRO', 'Acessório e componente homologado Show Tecnologia / Omnilink — OMNISAFE - SENSOR DE BAFOMETRO.', 956.34, 956.34, 0, '/products/prod-img-26.jpg', true, '{"allow_pix":true,"allow_boleto":true,"max_boleto_installments":3,"allow_card":true,"max_card_installments":12,"allow_financing":false}'::jsonb),
('prod-115', 'cat-2', 'CONTROLADOR DE TRAVA MOTORIZ. TURBO', 'Acessório e componente homologado Show Tecnologia / Omnilink — CONTROLADOR DE TRAVA MOTORIZ. TURBO.', 578.55, 578.55, 0, '/products/prod-img-27.jpg', true, '{"allow_pix":true,"allow_boleto":true,"max_boleto_installments":3,"allow_card":true,"max_card_installments":12,"allow_financing":false}'::jsonb),
('prod-116', 'cat-2', 'SENSOR CABINE CONTATO - MR - CJ RASTREADOR', 'Acessório e componente homologado Show Tecnologia / Omnilink — SENSOR CABINE CONTATO - MR - CJ RASTREADOR.', 19.95, 19.95, 0, '/products/prod-img-28.jpg', true, '{"allow_pix":true,"allow_boleto":true,"max_boleto_installments":3,"allow_card":true,"max_card_installments":12,"allow_financing":false}'::jsonb),
('prod-117', 'cat-2', 'SENSOR MOVIMENTO PLATAFORMA', 'Acessório e componente homologado Show Tecnologia / Omnilink — SENSOR MOVIMENTO PLATAFORMA.', 241.88, 241.88, 0, '/products/prod-img-29.jpg', true, '{"allow_pix":true,"allow_boleto":true,"max_boleto_installments":3,"allow_card":true,"max_card_installments":12,"allow_financing":false}'::jsonb),
('prod-118', 'cat-2', 'SENSOR MOVIMENTO PLATAFORMA - MP - CJ TE PLAT', 'Acessório e componente homologado Show Tecnologia / Omnilink — SENSOR MOVIMENTO PLATAFORMA - MP - CJ TE PLAT.', 266.7, 266.7, 0, '/products/prod-img-30.jpg', true, '{"allow_pix":true,"allow_boleto":true,"max_boleto_installments":3,"allow_card":true,"max_card_installments":12,"allow_financing":false}'::jsonb),
('prod-119', 'cat-2', 'CARTAO SD 512GB - MDVR', 'Acessório e componente homologado Show Tecnologia / Omnilink — CARTAO SD 512GB - MDVR.', 1800, 1800, 0, '/products/prod-img-31.jpg', true, '{"allow_pix":true,"allow_boleto":true,"max_boleto_installments":3,"allow_card":true,"max_card_installments":12,"allow_financing":false}'::jsonb),
('prod-120', 'cat-2', 'CARTAO MICROSD 512GB - DASHCAM', 'Acessório e componente homologado Show Tecnologia / Omnilink — CARTAO MICROSD 512GB - DASHCAM.', 1507.8, 1507.8, 0, '/products/prod-img-32.jpg', true, '{"allow_pix":true,"allow_boleto":true,"max_boleto_installments":3,"allow_card":true,"max_card_installments":12,"allow_financing":false}'::jsonb),
('prod-121', 'cat-2', 'CJ TRAVA BAÚ FRIGORÍFICO - P. LATERAL', 'Acessório e componente homologado Show Tecnologia / Omnilink — CJ TRAVA BAÚ FRIGORÍFICO - P. LATERAL.', 1564.5, 1564.5, 0, '/products/prod-img-33.jpg', true, '{"allow_pix":true,"allow_boleto":true,"max_boleto_installments":3,"allow_card":true,"max_card_installments":12,"allow_financing":false}'::jsonb),
('prod-122', 'cat-2', 'CJ TRAVA BAÚ FRIGORÍFICO - P. TRASEIRA', 'Acessório e componente homologado Show Tecnologia / Omnilink — CJ TRAVA BAÚ FRIGORÍFICO - P. TRASEIRA.', 1757.7, 1757.7, 0, '/products/prod-img-34.jpg', true, '{"allow_pix":true,"allow_boleto":true,"max_boleto_installments":3,"allow_card":true,"max_card_installments":12,"allow_financing":false}'::jsonb),
('prod-123', 'cat-2', 'BOTAO DE PANICO COMPACTO', 'Acessório e componente homologado Show Tecnologia / Omnilink — BOTAO DE PANICO COMPACTO.', 59.85, 59.85, 0, '/products/prod-img-35.jpg', true, '{"allow_pix":true,"allow_boleto":true,"max_boleto_installments":3,"allow_card":true,"max_card_installments":12,"allow_financing":false}'::jsonb),
('prod-124', 'cat-2', 'ANTENA GPS EXTERNA (BASE MAGNETICA - CABO 3 METROS)', 'Acessório e componente homologado Show Tecnologia / Omnilink — ANTENA GPS EXTERNA (BASE MAGNETICA - CABO 3 METROS).', 195.3, 195.3, 0, '/products/prod-img-36.jpg', true, '{"allow_pix":true,"allow_boleto":true,"max_boleto_installments":3,"allow_card":true,"max_card_installments":12,"allow_financing":false}'::jsonb),
('prod-125', 'cat-2', 'KIT INSTALACAO RELE FULL TIME (24V)', 'Acessório e componente homologado Show Tecnologia / Omnilink — KIT INSTALACAO RELE FULL TIME (24V).', 130, 130, 0, '/products/prod-img-37.jpg', true, '{"allow_pix":true,"allow_boleto":true,"max_boleto_installments":3,"allow_card":true,"max_card_installments":12,"allow_financing":false}'::jsonb),
('prod-126', 'cat-2', 'KIT Perfil Omêga - VAN', 'Acessório e componente homologado Show Tecnologia / Omnilink — KIT Perfil Omêga - VAN.', 95.9, 95.9, 0, '/products/prod-img-38.jpg', true, '{"allow_pix":true,"allow_boleto":true,"max_boleto_installments":3,"allow_card":true,"max_card_installments":12,"allow_financing":false}'::jsonb),
('prod-127', 'cat-2', 'KIT SUPORTE RELE c/RELE', 'Acessório e componente homologado Show Tecnologia / Omnilink — KIT SUPORTE RELE c/RELE.', 58.95, 58.95, 0, '/products/prod-img-39.jpg', true, '{"allow_pix":true,"allow_boleto":true,"max_boleto_installments":3,"allow_card":true,"max_card_installments":12,"allow_financing":false}'::jsonb),
('prod-128', 'cat-2', 'CJ TRAVA MOTORIZADA CARRETA P TRAS. 02 FOLHAS (LEGADO)', 'Acessório e componente homologado Show Tecnologia / Omnilink — CJ TRAVA MOTORIZADA CARRETA P TRAS. 02 FOLHAS (LEGADO).', 1417.5, 1417.5, 0, '/products/prod-img-40.jpg', true, '{"allow_pix":true,"allow_boleto":true,"max_boleto_installments":3,"allow_card":true,"max_card_installments":12,"allow_financing":false}'::jsonb),
('prod-129', 'cat-2', 'TRAVA DE QUINTA RODA DIGITAL FONTAINE + ARIETE', 'Acessório e componente homologado Show Tecnologia / Omnilink — TRAVA DE QUINTA RODA DIGITAL FONTAINE + ARIETE.', 3700, 3700, 0, '/products/prod-img-129.jpg', true, '{"allow_pix":true,"allow_boleto":true,"max_boleto_installments":3,"allow_card":true,"max_card_installments":12,"allow_financing":false}'::jsonb)
ON CONFLICT (id) DO NOTHING;
